### ISSUE TITLE
Plugin works on zimbra-ose-10.0.8, but with exceptions

### ISSUE THREAD

**Issue by george-zhilyakov** [maldua-suite/zimbra-ose-2fa#19]
Automatic install and initial users configuration went fine, but while logging in to account mailbox log receives following exception:

```
2024-09-04 19:18:30,726 WARN  [qtp364604394-959://localhost:8080/service/soap/SendTwoFactorAuthCodeRequest] [name=user@domain.tld;mid=3;ua=ZCS/10.0.8_GA_0324;soapId=fc809c6;] SoapEngine - cannot dispatch request
com.zimbra.common.service.ServiceException: unknown document: SendTwoFactorAuthCodeRequest
        at com.zimbra.common.service.ServiceException.UNKNOWN_DOCUMENT(ServiceException.java:347) ~[zimbracommon.jar:10.0.8_GA_0324]
        at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:569) ~[zimbrastore.jar:10.0.8_GA_0324]
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:491) ~[zimbrastore.jar:10.0.8_GA_0324]
        at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:278) ~[zimbrastore.jar:10.0.8_GA_0324]
        at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:322) ~[zimbrastore.jar:10.0.8_GA_0324]
        at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:231) ~[zimbrastore.jar:10.0.8_GA_0324]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[servlet-api-3.1.jar:3.1.0]
        at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:214) ~[zimbrastore.jar:10.0.8_GA_0324]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292) ~[websocket-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:175) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:125) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:118) ~[zimbrastore.jar:10.0.8_GA_0324]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:487) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:336) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:301) ~[jetty-servlets-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571) ~[jetty-security-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322) ~[jetty-rewrite-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:80) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.46.v20220331.jar:9.4.46.v20220331]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2024-09-04 19:18:30,730 INFO  [qtp364604394-959://localhost:8080/service/soap/SendTwoFactorAuthCodeRequest] [name=user@domain.tld;mid=3;ua=ZCS/10.0.8_GA_0324;soapId=fc809c6;] soap - SendTwoFactorAuthCodeRequest elapsed=4
2024-09-04 19:18:30,731 WARN  [qtp364604394-420://mailsv3.domain.tld/] [] webclient - Two-factor authentication could not be executed.

```
Then user gets "Two factor code could not be initialized. Please try to login with username and password again." message on verification code screen:
![image](https://github.com/user-attachments/assets/e11eb0f5-890b-40c9-9246-3d0067179c85)

After entering the verification code user get logged in normally. So plugin works, except these annoying exection and error message. 

Do you have any ideas how we can fix this?

**Comment by adriangibanelbtactic** [comment]
Please share with us the complete output of: `zmcontrol -v` run as a Zimbra user so that we can check which Zimbra version you are actually using.

Thank you.

**Comment by george-zhilyakov** [comment]
Full version:
```
zmcontrol -v
Release 10.0.8_GA_0324.RHEL8_64_20240702110623 RHEL8_64 FOSS edition.

```
Thanks!

**Comment by george-zhilyakov** [comment]
Just reinstalled everything from scratch using distribution from  your project (https://maldua.github.io/zimbra-foss-builder/downloads.html) and it work with no issues.

Sorry for bothering!

**Comment by adriangibanelbtactic** [comment]
> Full version:
> 
> ```
> zmcontrol -v
> Release 10.0.8_GA_0324.RHEL8_64_20240702110623 RHEL8_64 FOSS edition.
> ```
> 
> Thanks!

That's an ianw1974's build of Zimbra Next. Here there is a more detailed explanation of why I don't support that: https://github.com/maldua-suite/zimbra-ose-2fa/issues/18#issuecomment-2286396807 .

**Comment by adriangibanelbtactic** [comment]
> Just reinstalled everything from scratch using distribution from your project (https://maldua.github.io/zimbra-foss-builder/downloads.html) and it work with no issues.
> 
> Sorry for bothering!

Can you please share what tgz file have you used?
`zmcontrol -v` output is ok too.

This way we will have a record of a Zimbra version that works ok with the *MALDUA'S Zimbra OSE 2FA Extension & Administration Zimlet*.

Thank you!

**Comment by george-zhilyakov** [comment]
This one works:
```
zmcontrol -v
Release 10.0.8_GA_4200000.RHEL8_64_20240422174847 RHEL8_64 FOSS edition.
```
`zcs-10.0.8_GA_4200000.RHEL8_64.20240422174847.tgz`

**Comment by adriangibanelbtactic** [comment]
> This one works:
> 
> ```
> zmcontrol -v
> Release 10.0.8_GA_4200000.RHEL8_64_20240422174847 RHEL8_64 FOSS edition.
> ```
> 
> `zcs-10.0.8_GA_4200000.RHEL8_64.20240422174847.tgz`

Nice. That's expected to work with the 2FA zimlet, yes.

I'll close the issue then.
