### ISSUE TITLE
java.io.FileNotFoundException: Zimlet not found when installing on single server

### ISSUE THREAD

**Issue by techworks-id** [maldua-suite/zimbra-ose-2fa#21]
Hi,

When i run install on single server i got this error

```
[root@mail zimbra-ose-2fa_0.8.0]# ./install.sh
java.io.FileNotFoundException: Zimlet not found: /root/zimbra-ose-2fa_0.8.0/com_btactic_twofactorauth_admin.zip
        at com.zimbra.cs.zimlet.ZimletFile.findZimlet(ZimletFile.java:363)
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:155)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1951)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2053)
2024-11-19 16:08:03,348 [main] ERROR: Error
java.io.FileNotFoundException: Zimlet not found: /root/zimbra-ose-2fa_0.8.0/com_btactic_twofactorauth_admin.zip
        at com.zimbra.cs.zimlet.ZimletFile.findZimlet(ZimletFile.java:363) ~[zimbrastore.jar:10.1.2_GA_4200000]
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:155) ~[zimbrastore.jar:10.1.2_GA_4200000]
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1951) [zimbrastore.jar:10.1.2_GA_4200000]
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2053) [zimbrastore.jar:10.1.2_GA_4200000]
```

that file confirm exist on that folder.
```
[root@oldmail zimbra-ose-2fa_0.8.0]# ll
total 364
-rw-r-----. 1 zimbra zimbra   6231 Jan 20  2024 com_btactic_twofactorauth_admin.zip
-rwxr-x---. 1 zimbra zimbra   2847 Jan 20  2024 install.sh
drwxr-x---. 2 zimbra zimbra     46 Jan 20  2024 qr
-rw-r-----. 1 zimbra zimbra 358396 Jan 20  2024 zetatwofactorauth.jar

```

**Comment by adriangibanelbtactic** [comment]
> When i run install on single server i got this error
> 
> ```
> [root@mail zimbra-ose-2fa_0.8.0]# ./install.sh
> java.io.FileNotFoundException: Zimlet not found: /root/zimbra-ose-2fa_0.8.0/com_btactic_twofactorauth_admin.zip
> (...)
> ```

Please check [documentation regarding installation](https://github.com/maldua-suite/zimbra-ose-2fa?tab=readme-ov-file#automatic-installation) before trying to install it on your own.

Changing into **/tmp** is done on purpose so that zimbra user can read the zip file properly.

> zimbra 10.1.x not supported yet.

That's right.
